// Generated by https://quicktype.io

import { EstadoCamion } from './estadoCamion';

export class Truck {
    idCamion            : number;
    patente             : string;
    marca               : string;
    capacidad           : number;
    fkidEstadoCamion    : EstadoCamion;
    constructor(truck) {
        this.idCamion         = truck.idCamion;
        this.patente          = truck.patente;
        this.marca            = truck.marca;
        this.capacidad        = truck.capacidad;
        this.fkidEstadoCamion = truck.fkidEstadoCamion;
    }
}



