// Generated by https://quicktype.io

export class Usuario {
    constructor(
        public name             : string,
        public apellido         : string,
        public correo           : string,
        public fechaCreacion    : string,
        public nombreUsuario    : string,
        public telefono         : string,
        public idUsuario?       : string,
    ){}
}