// Generated by https://quicktype.io

export interface AuthResponse {
    ok              : boolean;
    id?             : number;
    nombre?         : string;
    apellido?       : string;
    correo?         : string;
    token?          : string;
    fotoUsuario?    : string;
}

export interface Usuario{
    id: string;
    correo: string;
}
