// Generated by https://quicktype.io

export interface Usuario {
    FKTipoUsuario: FKTipoUsuario;
    apellido:      string;
    correo:        string;
    estadoUsuario: EstadoUsuario;
    fechaCreacion: string;
    idUsuario?:     string;
    nombreUsuario: string;
    password:      string;
    telefono:      string;
}

export interface FKTipoUsuario {
    idTipoUsuarios: number;
    nombre:         string;
}

export interface EstadoUsuario {
    idEstadoUsuarios: number;
    nombreEstado:     string;
}
